name: Build and Publish SoftCenter

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:11
    env:
      APP_VERSION: "1.0.${{ github.run_number }}"
      RELEASE_TAG: "v1.0.${{ github.run_number }}"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

    steps:
    - name: Prepare Container Environment
      env:
        DEBIAN_FRONTEND: noninteractive 
      run: |
        dpkg --add-architecture arm64
        apt-get update
        
        apt-get install -y git curl zip unzip clang gcc gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu zlib1g-dev:arm64 ca-certificates libicu-dev

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Install Dependencies
      run: dotnet restore

    - name: Publish Native AOT (linux-arm64)
      run: |
        dotnet publish -c Release -r linux-arm64 --self-contained true \
        /p:PublishAot=true \
        /p:Version=${{ env.APP_VERSION }} \
        /p:InformationalVersion=${{ env.APP_VERSION }} \
        /p:ObjCopyName=aarch64-linux-gnu-objcopy \
        /p:CppCompilerAndLinker=aarch64-linux-gnu-gcc

    - name: Zip the build
      run: |
        cp -r web bin/Release/net10.0/linux-arm64/publish/ || true
        cd bin/Release/net10.0/linux-arm64/publish/
        zip -r "$GITHUB_WORKSPACE/SoftCenter-v${{ env.APP_VERSION }}-arm64.zip" \
            SoftCenterManager \
            libe_sqlite3.so \
            web/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        name: Release ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false
        files: SoftCenter-v${{ env.APP_VERSION }}-arm64.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}