name: Build and Publish SoftCenter

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: "1.0.${{ github.run_number }}" 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Install Dependencies
      run: dotnet restore

    - name: Publish Native AOT (linux-arm64)
      run: |
        dotnet publish -c Release -r linux-arm64 --self-contained true \
        /p:PublishAot=true \
        /p:Version=${{ env.VERSION }} \
        /p:InformationalVersion=${{ env.VERSION }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SoftCenterManager-v${{ env.VERSION }}-arm64
        path: bin/Release/net10.0/linux-arm64/publish/SoftCenterManager